arm-swcomp-id = {
  arm.measurement-type => text
  arm.version => text
  arm.signer-id => arm.hash-type
}

arm.hash-type = bytes .size 32 / bytes .size 48 / bytes .size 64

arm.measurement-type = 1
arm.version = 4
arm.signer-id = 5